POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "010101",
  "password": "010101"
}

###
POST http://localhost:3000/register/resident
Content-Type: application/json
    
{
    "_id": "010505",
    "password": "010505",
    "name": "Lim",
    "apartment": "005",
    "mobile": "0174716406"
}

###
POST http://localhost:3000/remove/resident
Content-Type: application/json
    
{
    "_id": "010505",
    "apartment": "005"
}

###
POST http://localhost:3000/register/security
Content-Type: application/json
    
{
    "_id": "070707",
    "password": "070707",
    "name": "James Bond",
    "mobile": "007007007"
}

###
POST http://localhost:3000/remove/security
Content-Type: application/json
    
{
    "_id": "070707"
}

###

GET http://localhost:3000/dashboard/

###
GET http://localhost:3000/dashboard/pending

###
GET http://localhost:3000/dashboard/approved

###
GET http://localhost:3000/dashboard/rejected

###
GET http://localhost:3000/logout

###
GET http://localhost:3000/