
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "011018",
  "password": "011018"
}

###

POST http://localhost:3000/dashboard/create
Content-Type: application/json

{
    "name": "Wong",
    "carplate": "JQX3018",
    "identification": "88888",
    "mobile": "99999",
    "visitpurpose": "Meeting"
}

###
GET http://localhost:3000/dashboard/

###
GET http://localhost:3000/dashboard/pending

###
GET http://localhost:3000/dashboard/approved

###
GET http://localhost:3000/dashboard/rejected

###
GET http://localhost:3000/dashboard/history

###
POST http://localhost:3000/dashboard/approve
Content-Type: application/json

{
  "_id": "20230627104126"
}

###
POST http://localhost:3000/dashboard/reject
Content-Type: application/json

{
  "_id": "20230627104126",
  "reason": "Not a good guy"
}

###
GET http://localhost:3000/logout

###