POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "000000",
  "password": "000000"
}

###
GET http://localhost:3000/dashboard/

###
GET http://localhost:3000/dashboard/pending

###
GET http://localhost:3000/dashboard/approved

###
GET http://localhost:3000/dashboard/rejected

###
GET http://localhost:3000/dashboard/history

###
POST http://localhost:3000/checkin
Content-Type: application/json

{
  "_id": "20230627104126"
}

###
POST http://localhost:3000/checkout
Content-Type: application/json

{
  "_id": "20230627104126"
}

###
GET http://localhost:3000/logout

###