POST http://localhost:3000/visitor/new
Content-Type: application/json

{
    "host": "011018",
    "apartment": "001",
    "name": "Bon",
    "carplate": "JMS2060",
    "identification": "010831098888",
    "mobile": "01127389508",
    "visitpurpose": "general"
}

###
POST http://localhost:3000/visitor/status
Content-Type: application/json

{
    "_id": "20230627104126"
}